<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    
    <PropertyGroup Label="Nuget Settings">
        <Title>ShadcnBlazor</Title>
        <Authors>ChiaraBm</Authors>
        <Description>A port of shadcn to blazor</Description>
        <Copyright>ChiaraBm</Copyright>
        <PackageProjectUrl>https://github.com/ChiaraBm/ShadcnBlazor</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/ChiaraBm/ShadcnBlazor/blob/main/LICENSE.md</PackageLicenseUrl>
        <PackageIcon>logo.png</PackageIcon>
        <RepositoryUrl>https://github.com/ChiaraBm/ShadcnBlazor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>shadcn,blazor</PackageTags>
        <Version>1.0.19</Version>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="LucideBlazor" Version="1.0.6" />
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.19" />
        <PackageReference Include="TailwindMerge.NET" Version="1.4.0" />
    </ItemGroup>

    <ItemGroup>
      <None Include="..\Assets\logo.png">
        <Pack>True</Pack>
        <PackagePath>/</PackagePath>
        <Link>logo.png</Link>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="DataGrids\DataGrid.Loading.cs">
        <DependentUpon>DataGrid.razor</DependentUpon>
      </Compile>
      <Compile Update="DataGrids\DataGrid.Search.cs">
        <DependentUpon>DataGrid.razor</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup Label="Class map include">
        <None Include="Styles/*" Pack="true" PackagePath="Styles/" />
        <None Include="ShadcnBlazor.targets" Pack="true" PackagePath="build\ShadcnBlazor.targets" />
        <None Include="ShadcnBlazor.targets" Pack="true" PackagePath="buildTransitive\ShadcnBlazor.targets" />
    </ItemGroup>
</Project>
