<Project Sdk="Microsoft.NET.Sdk.Razor">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <PropertyGroup Label="Nuget Settings">
        <Title>ShadcnBlazor.Extras</Title>
        <Authors>ChiaraBm</Authors>
        <Description>Additional utilities and components for ShadcnBlazor</Description>
        <Copyright>ChiaraBm</Copyright>
        <PackageProjectUrl>https://github.com/ChiaraBm/ShadcnBlazor</PackageProjectUrl>
        <PackageLicenseUrl>https://github.com/ChiaraBm/ShadcnBlazor/blob/main/LICENSE.md</PackageLicenseUrl>
        <PackageIcon>logo.png</PackageIcon>
        <RepositoryUrl>https://github.com/ChiaraBm/ShadcnBlazor</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <PackageTags>shadcn,blazor</PackageTags>
        <Version>1.0.19</Version>
    </PropertyGroup>

    <ItemGroup>
        <None Include="..\Assets\logo.png">
            <Pack>True</Pack>
            <PackagePath>/</PackagePath>
            <Link>logo.png</Link>
        </None>
        <None Remove="CodeMirror\**" />
    </ItemGroup>
    
    <ItemGroup>
        <SupportedPlatform Include="browser"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.19" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ShadcnBlazor\ShadcnBlazor.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Compile Remove="CodeMirror\**" />
      <EmbeddedResource Remove="CodeMirror\**" />
      <Content Remove="CodeMirror\**" />
      <Compile Update="FileManagers\FileManager.Navigation.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
      <Compile Update="FileManagers\FileManager.ContextMenu.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
      <Compile Update="FileManagers\FileManager.Toolbar.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
      <Compile Update="FileManagers\FileManager.Operations.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
      <Compile Update="FileManagers\FileManager.Selection.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
      <Compile Update="FileManagers\FileManager.Open.cs">
        <DependentUpon>FileManager.razor</DependentUpon>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="CodeMirror\package-lock.json" />
      <_ContentIncludedByDefault Remove="CodeMirror\package.json" />
    </ItemGroup>

</Project>
